# Generated by Django 2.1.7 on 2019-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('url', models.URLField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
