# Generated by Django 2.1.7 on 2019-03-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
