# Generated by Django 2.1.7 on 2019-03-13 17:45

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File
from django.utils.text import slugify

def load_book_data(apps, schema_editor):
    """Read a CSV file of books and add to database"""
    Book = apps.get_model('core', 'Book')
    datapath = os.path.join(settings.BASE_DIR, 'initial_data')
    datafile = os.path.join(datapath, 'books.csv')

    with open(datafile) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book_title = row['title']
            # Don't create book if title matches existing record
            if Book.objects.filter(title=book_title).count():
                continue
            book = Book(
                title = row['title'],
                author = row['author'],
                description = row['description'],
                url = row['url'],
                category = row['category'],
                slug = slugify(row['title'])
            )
            book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190312_1316'),
    ]

    operations = [
        migrations.RunPython(load_book_data)
    ]
