# Generated by Django 2.1.7 on 2019-03-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
