# Generated by Django 2.1.7 on 2019-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='book',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
