# Generated by Django 2.1.7 on 2019-03-16 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_book_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_books', through='core.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
